### ISSUE TITLE
"user homebrew_owner" breaks Cask on Mountain Lion

### ISSUE THREAD

**Issue by jgoldschrafe** [opscode-cookbooks/homebrew#48]
When specifying a non-root user for Cask on Mountain Lion, the following error is produced:

    STDERR: Error: Empty result parsing plist output from command.
             command was:
             ["/usr/bin/hdiutil", "mount", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/tmp", #<Pathname:/Library/Caches/Homebrew/whatever.dmg>]
             output we attempted to parse:
             hdiutil: mount failed - Device not configured

Everything works fine and dandy with the cookbook running inside of root's bootstrap context.

**Comment by jtimberman** [comment]
I fixed a bug (#61) in the class used by this cookbook's `homebrew_owner` method. Can you give it a go and see if it corrects the issue?
