### ISSUE TITLE
Incorrect permissions on /opt/homebrew-cask and subfolders

### ISSUE THREAD

**Issue by ringods** [opscode-cookbooks/homebrew#52]
When installing the ``java7`` cask, I bumped into permission errors on ``/opt/homebrew-cask`` folder and subfolders. 

```STDERR: Error: Permission denied - /opt/homebrew-cask/Caskroom/java7```

This folder structure was owned by ``root``, not the Homebrew owner.

Looking at the [Pivotal Sprout Cask recipe](https://github.com/pivotal-sprout/sprout-homebrew/blob/master/recipes/cask.rb#L20), I noticed they set the permissions on this folder explicitely to the Homebrew owner, in their case the current user.

The ``cask`` recipe needs to be extended with a similar setup. I validated manually that setting the permissions on the folder fixed the installation process of the cask.

**Comment by mkcode** [comment]
+1 on having /opt/homebrew-cask/Caskroom managed by this repo. Ran into this issue and overriding ['home-brew']['owner'] does not fix the problem for me.
