### ISSUE TITLE
add options to homebrew_cask

### ISSUE THREAD

**Issue by bcg62** [opscode-cookbooks/homebrew#68]
I used to work around this by doing something like:

homebrew_cask 'iterm2 --appdir=/Applications'

except now it seems this is prevented by regex validation:

chef 12.1.0:
```
Chef::Exceptions::ValidationFailed
---------------------------------
Option name's value iterm2 --appdir=/Applications does not match regular expression /^[\w-]+$/
```

Ideally the LWRP should support option passing

homebrew_cask 'iterm2' do
  options '--appdir=/Applications'
end

**Comment by tarak** [comment]
+1. The cask LWRP is not usable without the ability to customize cask.
